kind: Deployment
apiVersion: apps/v1
metadata:
  name: gty-nginx
  namespace: default
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '2'
    description: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gty-nginx
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gty-nginx
        version: v1
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"prometheus","path":"/metrics","port":"8080","names":["cpu_usage","mem_usage"]}]'
    spec:
      containers:
        - name: container-0
          image: 'nginx:perl'
          env:
            - name: PAAS_APP_NAME
              value: nginx
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: dd3b293b96754669bea812967e195467
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 123
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 123
      dnsConfig:
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
