apiVersion: apps/v1
kind: Deployment
metadata:
  name: gty-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gty-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
